// Generated by jextract

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*_purecall_handler)();
 * }
 */
public interface _purecall_handler {

    void apply();
    static MemorySegment allocate(_purecall_handler fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$18._purecall_handler_UP$MH, fi, constants$18._purecall_handler$FUNC, scope);
    }
    static _purecall_handler ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return () -> {
            try {
                constants$18._purecall_handler_DOWN$MH.invokeExact(symbol);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


