// Generated by jextract

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$43 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$43() {}
    static final FunctionDescriptor new_$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_LONG_LONG$LAYOUT.withName("x"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("y"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("z"),
        Constants$root.C_DOUBLE$LAYOUT.withName("k0"),
        Constants$root.C_DOUBLE$LAYOUT.withName("k1")
    ).withName("State"),
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle new_$MH = RuntimeHelper.downcallHandle(
        "new",
        constants$43.new_$FUNC
    );
    static final FunctionDescriptor full$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_LONG_LONG$LAYOUT.withName("x"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("y"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("z"),
        Constants$root.C_DOUBLE$LAYOUT.withName("k0"),
        Constants$root.C_DOUBLE$LAYOUT.withName("k1")
    ).withName("State"),
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle full$MH = RuntimeHelper.downcallHandle(
        "full",
        constants$43.full$FUNC
    );
    static final MemorySegment NULL$ADDR = MemorySegment.ofAddress(0L);
    static final MemorySegment __FILEW__$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("C");
}


