// Generated by jextract

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct State {
 *     int64_t x;
 *     int64_t y;
 *     int64_t z;
 *     double k0;
 *     double k1;
 * };
 * }
 */
public class State {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG_LONG$LAYOUT.withName("x"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("y"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("z"),
        Constants$root.C_DOUBLE$LAYOUT.withName("k0"),
        Constants$root.C_DOUBLE$LAYOUT.withName("k1")
    ).withName("State");
    public static MemoryLayout $LAYOUT() {
        return State.$struct$LAYOUT;
    }
    static final VarHandle x$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("x"));
    public static VarHandle x$VH() {
        return State.x$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int64_t x;
     * }
     */
    public static long x$get(MemorySegment seg) {
        return (long)State.x$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int64_t x;
     * }
     */
    public static void x$set(MemorySegment seg, long x) {
        State.x$VH.set(seg, x);
    }
    public static long x$get(MemorySegment seg, long index) {
        return (long)State.x$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void x$set(MemorySegment seg, long index, long x) {
        State.x$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle y$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("y"));
    public static VarHandle y$VH() {
        return State.y$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int64_t y;
     * }
     */
    public static long y$get(MemorySegment seg) {
        return (long)State.y$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int64_t y;
     * }
     */
    public static void y$set(MemorySegment seg, long x) {
        State.y$VH.set(seg, x);
    }
    public static long y$get(MemorySegment seg, long index) {
        return (long)State.y$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void y$set(MemorySegment seg, long index, long x) {
        State.y$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle z$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("z"));
    public static VarHandle z$VH() {
        return State.z$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int64_t z;
     * }
     */
    public static long z$get(MemorySegment seg) {
        return (long)State.z$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int64_t z;
     * }
     */
    public static void z$set(MemorySegment seg, long x) {
        State.z$VH.set(seg, x);
    }
    public static long z$get(MemorySegment seg, long index) {
        return (long)State.z$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void z$set(MemorySegment seg, long index, long x) {
        State.z$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle k0$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("k0"));
    public static VarHandle k0$VH() {
        return State.k0$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * double k0;
     * }
     */
    public static double k0$get(MemorySegment seg) {
        return (double)State.k0$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * double k0;
     * }
     */
    public static void k0$set(MemorySegment seg, double x) {
        State.k0$VH.set(seg, x);
    }
    public static double k0$get(MemorySegment seg, long index) {
        return (double)State.k0$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void k0$set(MemorySegment seg, long index, double x) {
        State.k0$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle k1$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("k1"));
    public static VarHandle k1$VH() {
        return State.k1$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * double k1;
     * }
     */
    public static double k1$get(MemorySegment seg) {
        return (double)State.k1$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * double k1;
     * }
     */
    public static void k1$set(MemorySegment seg, double x) {
        State.k1$VH.set(seg, x);
    }
    public static double k1$get(MemorySegment seg, long index) {
        return (double)State.k1$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void k1$set(MemorySegment seg, long index, double x) {
        State.k1$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


